CREATE DATABASE MunicipalApp;

CREATE TABLE ISSUE_REPORTS(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	LOCATION NVARCHAR(MAX),
	DESCRIPTION NVARCHAR(MAX),
	CATEGORY NVARCHAR(100),
	SOLUTION NVARCHAR(MAX),
	ATTACHMENTS VARBINARY(MAX)
);