//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Municipal_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISSUE_REPORT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ISSUE_REPORT()
        {
            this.ATTACHMENTs = new HashSet<ATTACHMENT>();
        }
    
        public int ID { get; set; }
        public string LOCATION { get; set; }
        public string DESCRIPTION { get; set; }
        public string CATEGORY { get; set; }
        public string SOLUTION { get; set; }
        public string IDENTIFIER { get; set; }
        public string STATUS_STRING { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTACHMENT> ATTACHMENTs { get; set; }
    }
}
